import argparse

parser = argparse.ArgumentParser(description='MSBT')
parser.add_argument('--rgb-list', default='list/rgb.list', help='list of rgb features ')
parser.add_argument('--flow-list', default='list/flow.list', help='list of flow features')
parser.add_argument('--audio-list', default='list/audio.list', help='list of audio features')
parser.add_argument('--test-rgb-list', default='list/rgb_test.list', help='list of test rgb features ')
parser.add_argument('--test-flow-list', default='list/flow_test.list', help='list of test flow features')
parser.add_argument('--test-audio-list', default='list/audio_test.list', help='list of test audio features')
parser.add_argument('--gt', default='list/gt.npy', help='file of ground truth ')
parser.add_argument('--gpus', default='0', type=str,  help='gpus')
parser.add_argument('--lr', type=float, default=0.005)
parser.add_argument('--batch-size', type=int, default=128, help='number of instances in a batch of data (default: 128)')
parser.add_argument('--workers', default=8, help='number of workers in dataloader')
parser.add_argument('--model-name', default='MSBT', help='name to save model')
parser.add_argument('--a_feature_size', type=int, default=128)
parser.add_argument('--v_feature_size', type=int, default=1024)
parser.add_argument('--f_feature_size', type=int, default=1024)
parser.add_argument('--max_seqlen', type=int, default=200, help='maximum sequence length during training (default: 750)')
parser.add_argument('--max_epoch', type=int, default=50)
parser.add_argument('--hid_dim', type=int, default=128)
parser.add_argument('--ffn_dim', type=int, default=128)
parser.add_argument('--nhead', type=int, default=4)
parser.add_argument('--dropout', type=float, default=0.2)
parser.add_argument('--n_transformer_layer', type=int, default=4)
parser.add_argument('--lambda_infoNCE', type=float, default=0.1)
parser.add_argument('--n_bottleneck', type=int, default=16)
parser.add_argument('--seed', type=int, default=0)
parser.add_argument('--bottleneck_std', type=float, default=0.15)
parser.add_argument('--MIL_dropout', type=float, default=0.6)
parser.add_argument('--eval', action="store_true")
parser.add_argument('--model_path', default='ckpt/MSBT_best_84.32.pkl')